export const foldersData = [
  {
    id: "f1",
    num: "1",
    sub: "10+",
    desc: "Files in recycle bin",
  },
  {
    id: "f2",
    num: "2",
    sub: "3+",
    desc: "Recent docs added",
  },
  {
    id: "f3",
    num: "3",
    sub: "2+",
    desc: "New docs shared with you",
  },
];

export const tableData = [
  {
    id: "t1",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t2",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t3",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t4",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t5",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t6",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t7",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t8",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t9",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t10",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t11",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t12",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t13",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t14",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t15",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t16",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t17",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t18",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t19",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t20",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t21",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
  {
    id: "t22",
    name: "qwerty",
    date: "12/12/2023",
    lab: "Dr. Path Labs",
    doctor: "Dr. Roshan",
  },
];
