const SUMMARY_PROMPT =
  "You are analysing a document that has been uploaded to a personal health records app. First, determine whether this document is a medical or health-related document (e.g. lab report, prescription, medical invoice, doctor's note, vaccination record, medical certificate). If it is NOT a medical document, respond only with a brief statement that you cannot analyse it because it is not a medical document — do not describe its contents, do not guess what it is, and do not provide any summary of it. If it IS a medical document, summarise it in plain language using only the information explicitly present in the document. List notable values, dates, medications, and any follow-up actions the document itself mentions. Do not diagnose, do not infer or assume information that is not explicitly stated, and do not speculate about causes, severity, or next steps beyond what the document says. If any part of the document is unclear or ambiguous, state that explicitly rather than guessing. Any follow-up questions the user asks about this document must be answered using only the information contained in the document itself — do not draw on outside medical knowledge to answer them. If you are not certain the document contains enough information to answer a follow-up question confidently, say so clearly and suggest the user consult a doctor rather than guessing.";

const BOUNDARY_PROMPT_PREFIX =
  "You are analysing a document that has been uploaded to a personal health records app. First, determine whether this document is a medical or health-related document (e.g. lab report, prescription, medical invoice, doctor's note, vaccination record, medical certificate). If it is NOT a medical document, respond only with a brief statement that you cannot analyse it because it is not a medical document — do not describe its contents, do not guess what it is, and do not provide any summary of it. If it IS a medical document, answer strictly using only the information explicitly present in the document. Do not diagnose, do not infer or assume information that is not explicitly stated, and do not speculate about causes, severity, or next steps beyond what the document says. If you are not certain the document contains enough information to answer confidently, say so clearly and suggest the user consult a doctor rather than guessing.";

function buildAskPrompt(question) {
  return `${BOUNDARY_PROMPT_PREFIX}\n\nUser's question: ${question}`;
}

const METRICS_EXTRACTION_PROMPT =
  "You are extracting structured data from a document uploaded to a personal health records app. First, determine whether this document is a medical or health-related document (e.g. lab report, prescription, medical invoice, doctor's note, vaccination record, medical certificate). If it is NOT a medical document, return an empty array. If it IS a medical document, extract every quantifiable test result or measurement explicitly stated in the document (e.g. cholesterol, hemoglobin, blood pressure, glucose, weight). For each one, return an object with: testName (lowercase, normalized, e.g. 'cholesterol' not 'Total Cholesterol'), value (a number only, no units), unit (e.g. 'mg/dL', 'g/dL', as written in the document), date (the date the test/measurement was taken, in YYYY-MM-DD format — if no specific date is given for a value, omit the date field rather than guessing), and rawLabel (the original text label as it appeared in the document, for display purposes). Only include values explicitly present in the document — do not infer, estimate, or calculate values that aren't directly stated. If a value has no discernible unit or number, omit it entirely rather than guessing. Return only the JSON array, nothing else.";

const CLASSIFICATION_PROMPT =
  "You are classifying a document uploaded to a personal health records app. Determine whether this document is a genuine medical or health-related document — meaning it has the structure, formatting, and context of an actual clinical document (e.g. a lab report with test results and reference ranges, a prescription with medication and dosage, a doctor's visit note with clinical observations, a vaccination record, a medical certificate). Do not classify a document as medical simply because it mentions health-related words or numbers — judge based on whether it is structured and presented as an authentic clinical or medical record (e.g. letterhead, provider/patient fields, report formatting, clinical terminology used in context). A resume, personal note, invoice, or any other document that merely references health topics, medical terms, or numbers without being an actual clinical document should NOT be classified as medical. Return isMedicalDocument (true/false), documentType (one of: lab_report, prescription, doctor_note, vaccination_record, medical_certificate, other), and confidence (high/medium/low — use 'low' whenever the document is ambiguous or you are not confident in the classification).";

module.exports = {
  SUMMARY_PROMPT,
  BOUNDARY_PROMPT_PREFIX,
  METRICS_EXTRACTION_PROMPT, // add to existing exports
  CLASSIFICATION_PROMPT,
  buildAskPrompt,
};
